global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using WebAPI.Controllers;
global using Microsoft.AspNetCore.Mvc;
global using Moq;
global using DAL;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using WebAPI.Helpers;
global using Assert = Microsoft.VisualStudio.TestTools.UnitTesting.Assert;
global using Microsoft.AspNetCore.Http;
global using Shared.Objects;
global using System.Drawing;
global using System.Drawing.Imaging;